name: tdd_education_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2

  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  file_picker: ^6.1.1
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.6
  iconly: ^1.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  url_launcher: ^6.2.3
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
