name: tdd_education_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2
  flutter_tindercard:
    git:
      url: https://github.com/NonymousMorlock/flutter_tindercard.git
  file_icon:
    git:
      url: https://github.com/NonymousMorlock/file_icon
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  file_picker: ^8.0.3
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.6
  iconly: ^1.0.1
  image_picker: ^1.0.7
  intl: ^0.18.0
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  url_launcher: ^6.2.3
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_ui_auth: ^1.7.0
  uuid: ^4.3.3
  badges: ^3.1.2
  audioplayers: ^6.0.0
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2

dependency_overrides:
  firebase_auth: "4.12.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.4.8
  firebase_storage_mocks: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/sounds/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
